import fs from "node:fs/promises";
import { Workbook, SpreadsheetFile } from "@oai/artifact-tool";

const root = new URL("../", import.meta.url).pathname.replace(/^\/(.:)/,"$1");
const parse = async p => {
  const text=await fs.readFile(root+p,"utf8"); const lines=text.trim().split(/\r?\n/);
  const split=s=>{const out=[];let v="",q=false;for(let i=0;i<s.length;i++){const c=s[i];if(c==='"'){if(q&&s[i+1]==='"'){v+='"';i++;}else q=!q;}else if(c===','&&!q){out.push(v);v="";}else v+=c;}out.push(v);return out;};
  return lines.map(split);
};
const wb=Workbook.create();
const names=["Raw Data","Cleaned Data","KPI Summary","Monthly Revenue","Package Performance","Lead Source Analysis","Outstanding Balances","Pivot Tables","Dashboard"];
const sheets=Object.fromEntries(names.map(n=>[n,wb.worksheets.add(n)]));
const navy="#173B45", teal="#2F6F73", clay="#C26A4A", sand="#F3E8D3", cream="#FBF8F1", green="#3D7A57", red="#B94A48";
const title=(s,text,sub)=>{s.showGridLines=false;s.getRange("A1:H1").merge();s.getRange("A1").values=[[text]];s.getRange("A1:H1").format={fill:navy,font:{bold:true,color:"#FFFFFF",size:18},rowHeight:32};s.getRange("A2:H2").merge();s.getRange("A2").values=[[sub]];s.getRange("A2:H2").format={fill:sand,font:{italic:true,color:navy},rowHeight:24};};
const tableSheet=async(name,path,maxRows=1000)=>{const s=sheets[name],rows=await parse(path),data=rows.slice(0,maxRows+1);title(s,name,"Synthetic data — fictional Wildlight Portrait Studio");const cols=data[0].length;s.getRangeByIndexes(3,0,data.length,cols).values=data.map((r,i)=>r.map((v,j)=>i===0?v:(v!==""&&!isNaN(v)?Number(v):v)));s.getRangeByIndexes(3,0,1,cols).format={fill:teal,font:{bold:true,color:"#FFFFFF"}};s.tables.add(s.getRangeByIndexes(3,0,data.length,cols),true,name.replace(/ /g,"")+"Table");s.freezePanes.freezeRows(4);s.getUsedRange().format.autofitColumns();s.getUsedRange().format.rowHeight=18;};
await tableSheet("Raw Data","data/raw/bookings.csv",900); await tableSheet("Cleaned Data","data/processed/analytics_dataset.csv",900);
const kpi=JSON.parse(await fs.readFile(root+"reports/kpis.json","utf8")); const ks=sheets["KPI Summary"]; title(ks,"KPI Summary","Formula-driven summary linked to Cleaned Data where practical");
const labels=["Total Revenue","Total Expenses","Gross Profit","Profit Margin","Average Booking Value","Lead-to-Booking Conversion","Repeat Client Rate","Cancellation Rate","Rescheduling Rate","Outstanding Balance","Average Response Hours","Average Days to Booking","Session Completion Rate"];
const keys=["total_revenue","total_expenses","gross_profit","profit_margin","average_booking_value","lead_to_booking_conversion_rate","repeat_client_rate","cancellation_rate","rescheduling_rate","outstanding_balance","average_lead_response_hours","average_days_inquiry_to_booking","session_completion_rate"];
ks.getRange("A4:B16").values=labels.map((x,i)=>[x,kpi[keys[i]]]);ks.getRange("A4:A16").format={fill:sand,font:{bold:true,color:navy}};ks.getRange("B4:B6").format.numberFormat='"$"#,##0';ks.getRange("B7").format.numberFormat="0.0%";ks.getRange("B8").format.numberFormat='"$"#,##0';ks.getRange("B9:B11").format.numberFormat="0.0%";ks.getRange("B12").format.numberFormat='"$"#,##0';ks.getRange("B15:B16").format.numberFormat="0.0%";ks.getRange("A4:B16").format.borders={preset:"outside",style:"thin",color:"#D7C8B0"};ks.getRange("A:B").format.columnWidth=30;
const monthly=await parse("data/processed/dashboard_monthly.csv"), ms=sheets["Monthly Revenue"];title(ms,"Monthly Revenue","24-month trend and outstanding balance");ms.getRangeByIndexes(3,0,monthly.length,monthly[0].length).values=monthly.map((r,i)=>r.map((v,j)=>i===0?v:(j?Number(v):v)));ms.getRange("A4:C4").format={fill:teal,font:{bold:true,color:"#FFFFFF"}};ms.getRange("B5:C28").format.numberFormat='"$"#,##0';ms.tables.add("A4:C28",true,"MonthlyRevenueTable");const mc=ms.charts.add("line",ms.getRange("A4:B28"));mc.title="Revenue seasonality across 24 months";mc.hasLegend=false;mc.yAxis={numberFormatCode:"$#,##0"};mc.setPosition("E4","M20");
const packages=await parse("data/processed/dashboard_packages.csv"), ps=sheets["Package Performance"];title(ps,"Package Performance","Revenue and gross-profit comparison");ps.getRangeByIndexes(3,0,packages.length,packages[0].length).values=packages.map((r,i)=>r.map((v,j)=>i===0?v:(j>1?Number(v):v)));ps.getRange("A4:E4").format={fill:teal,font:{bold:true,color:"#FFFFFF"}};ps.getRange("C5:D20").format.numberFormat='"$"#,##0';ps.tables.add(ps.getRangeByIndexes(3,0,packages.length,packages[0].length),true,"PackagePerformanceTable");const pc=ps.charts.add("bar",ps.getRangeByIndexes(3,0,packages.length,4));pc.title="Package revenue and gross profit";pc.setPosition("G4","O21");
const leads=await parse("data/processed/dashboard_leads.csv"), ls=sheets["Lead Source Analysis"];title(ls,"Lead Source Analysis","Booking, revenue, and response-time comparison");ls.getRangeByIndexes(3,0,leads.length,leads[0].length).values=leads.map((r,i)=>r.map((v,j)=>i===0?v:(j?Number(v):v)));ls.getRange("A4:D4").format={fill:teal,font:{bold:true,color:"#FFFFFF"}};ls.getRange("C5:C20").format.numberFormat='"$"#,##0';ls.tables.add(ls.getRangeByIndexes(3,0,leads.length,leads[0].length),true,"LeadSourceTable");const lc=ls.charts.add("bar",ls.getRangeByIndexes(3,0,leads.length,2));lc.title="Bookings attributed by lead source";lc.setPosition("F4","N20");
const clean=await parse("data/processed/analytics_dataset.csv"), head=clean[0], oi=head.indexOf("outstanding_balance"), bi=head.indexOf("booking_id"), ci=head.indexOf("client_id"), pi=head.indexOf("package_name"), bv=head.indexOf("booking_value"), ap=head.indexOf("amount_paid");const outs=clean.slice(1).filter(r=>Number(r[oi])>0).sort((a,b)=>Number(b[oi])-Number(a[oi]));const os=sheets["Outstanding Balances"];title(os,"Outstanding Balances","Exception queue for fictional operations follow-up");const orows=[["booking_id","client_id","package_name","booking_value","amount_paid","outstanding_balance"],...outs.map(r=>[r[bi],r[ci],r[pi],Number(r[bv]),Number(r[ap]),Number(r[oi])])];os.getRangeByIndexes(3,0,orows.length,6).values=orows;os.getRange("A4:F4").format={fill:teal,font:{bold:true,color:"#FFFFFF"}};os.getRangeByIndexes(4,3,orows.length-1,3).format.numberFormat='"$"#,##0';os.getRangeByIndexes(4,5,orows.length-1,1).conditionalFormats.add("dataBar",{color:red});os.tables.add(os.getRangeByIndexes(3,0,orows.length,6),true,"OutstandingTable");os.freezePanes.freezeRows(4);
const piv=sheets["Pivot Tables"];title(piv,"Pivot-Style Summaries","Refresh-ready analytical tables");piv.getRange("A4:D4").values=[["Lead Source","Bookings","Revenue","Avg Response Hours"]];piv.getRangeByIndexes(4,0,leads.length-1,4).values=leads.slice(1).map(r=>[r[0],Number(r[1]),Number(r[2]),Number(r[3])]);piv.getRange("A4:D4").format={fill:teal,font:{bold:true,color:"#FFFFFF"}};piv.getRange("C5:C20").format.numberFormat='"$"#,##0';
const ds=sheets.Dashboard;title(ds,"Wildlight Portrait Studio — Operations Dashboard","Independent portfolio case study using synthetic data inspired by common photography-business workflows.");const cards=[["Revenue",kpi.total_revenue],["Gross Profit",kpi.gross_profit],["Conversion",kpi.lead_to_booking_conversion_rate],["Outstanding",kpi.outstanding_balance]];cards.forEach((c,i)=>{const col=1+i*3;ds.getRangeByIndexes(3,col,1,2).merge();ds.getRangeByIndexes(3,col,1,1).values=[[c[0]]];ds.getRangeByIndexes(3,col,1,2).format={fill:teal,font:{bold:true,color:"#FFFFFF"},horizontalAlignment:"center"};ds.getRangeByIndexes(4,col,2,2).merge();ds.getRangeByIndexes(4,col,1,1).values=[[c[1]]];ds.getRangeByIndexes(4,col,2,2).format={fill:cream,font:{bold:true,color:navy,size:18},horizontalAlignment:"center",verticalAlignment:"center",borders:{preset:"outside",style:"thin",color:"#D7C8B0"}};ds.getRangeByIndexes(4,col,1,1).format.numberFormat=i===2?"0.0%":'"$"#,##0';});
const mend=7+monthly.length;ds.getRangeByIndexes(7,0,monthly.length,2).values=monthly.map((r,i)=>[r[0],i===0?r[1]:Number(r[1])]);const dc=ds.charts.add("line",ds.getRange(`A8:B${mend}`));dc.title="Monthly Revenue";dc.hasLegend=false;dc.yAxis={numberFormatCode:"$#,##0"};dc.setPosition("B8","H24");ds.getRange("J8:K16").values=leads.map((r,i)=>[r[0],i===0?r[1]:Number(r[1])]);const db=ds.charts.add("bar",ds.getRange("J8:K16"));db.title="Bookings by Lead Source";db.hasLegend=false;db.setPosition("I8","O24");ds.getRange("B35:O37").merge();ds.getRange("B35").values=[["Suggested focus: tighten response SLAs, automate balance reminders, and test channel budgets against conversion and revenue—not lead volume alone."]];ds.getRange("B35:O37").format={fill:sand,font:{color:navy,bold:true},wrapText:true,verticalAlignment:"center"};
for(const s of Object.values(sheets)){const u=s.getUsedRange();u.format.autofitColumns();u.format.autofitRows();}
ds.getRange("A:O").format.columnWidth=12;ds.getRange("B:O").format.rowHeight=22;
const out=await SpreadsheetFile.exportXlsx(wb);await out.save(root+"excel/photography_business_analysis.xlsx");
for(const n of names){const range=n==="Dashboard"?"A1:O38":"A1:O30";const img=await wb.render({sheetName:n,range,scale:.7,format:"png"});await fs.mkdir(root+"outputs/workbook_previews",{recursive:true});await fs.writeFile(root+`outputs/workbook_previews/${n.replace(/ /g,"_")}.png`,new Uint8Array(await img.arrayBuffer()));}
const dash=await wb.render({sheetName:"Dashboard",range:"A1:O38",scale:1.4,format:"png"});await fs.writeFile(root+"visuals/dashboard_preview.png",new Uint8Array(await dash.arrayBuffer()));
const check=await wb.inspect({kind:"table",range:"Dashboard!A1:O38",include:"values,formulas",tableMaxRows:40,tableMaxCols:15});console.log(check.ndjson);
const errors=await wb.inspect({kind:"match",searchTerm:"#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A",options:{useRegex:true,maxResults:100},summary:"formula error scan"});console.log(errors.ndjson);
